# baseURL = ''
languageCode = 'nl'
title = 'Demonstreer spontaan!'
author = 'Werkgroep Spontane Demonstratie'
description = "Spontane demonstraties zijn energiek en effectief. Je mag in Nederland gewoon spontaan demonstreren. Dus grijp die kans, demonstreer spontaan!"

[assetTypes]
    css = "text/css"

[markup]
    [markup.styles]
        postCSS = "assets/css/tailwind.css"

[params]
    ogImage = "/images/placard.png"
    ogImageAlt = "Lijntekening van een persoon met een bord, waarop staat 'Demonstreer spontaan'"
    description = "Spontane demonstraties zijn energiek en effectief. Je mag in Nederland gewoon spontaan demonstreren. Dus grijp die kans, demonstreer spontaan!"

[params.meta]
    favicon = true
